version: '3.8'

services:
  db:
    image: bitnami/postgresql:16
    restart: always
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - odoo-db-data:/bitnami/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5454:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  odoo:
    image: bitnami/odoo:17
    ports:
      - "${ODOO_HOST_PORT}:8069"
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - ./addons:/bitnami/odoo/extra-addons
      - ./etc:/bitnami/odoo/conf
    restart: always

volumes:
  odoo-db-data:
  pgadmin-data:
  odoo-addons:
  odoo-config:
