version: '2'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=merqconsultancy
      - POSTGRES_PASSWORD=merqhqadmin
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=merqconsultancy
      - PASSWORD=merqhqadmin
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@merqconsultancy.org
      - PGADMIN_DEFAULT_PASSWORD=merqhqadmin
    ports:
      - "5434:80" # adjust the port as needed
    restart: always
